services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    environment:
      KC_HOSTNAME: 18.135.49.118

      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/key.pem

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start", "--http-port", "80", "--https-port", "443", "--optimized"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./keycloak/certs:/etc/x509/https:ro
    networks:
      - kc_poc

  saml-app:
    build:
      context: .
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    networks:
      - kc_poc

networks:
  kc_poc:
    driver: bridge